//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyChat.Devices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLocation
    {
        public int Id { get; set; }
        public System.DateTime CreatedUTC { get; set; }
        public Nullable<System.DateTime> ModifiedUtc { get; set; }
        public byte[] Version { get; set; }
        public long VersionNumber { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public int DeviceId { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
