//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyChat.Devices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceLocations = new HashSet<DeviceLocation>();
            this.DeviceTokens = new HashSet<DeviceToken>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedUTC { get; set; }
        public Nullable<System.DateTime> ModifiedUTC { get; set; }
        public byte[] Version { get; set; }
        public long VersionNumber { get; set; }
        public string DeviceIdentifier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceLocation> DeviceLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceToken> DeviceTokens { get; set; }
    }
}
